---
- name: Validate distribution and role variables
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate/validate.yml"
  tags: nginx_validate

- name: Set up prerequisites
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/prerequisites/prerequisites.yml"
  when: nginx_state != 'absent'
  tags: nginx_prerequisites

- name: Set up signing keys
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/keys/setup-keys.yml"
  when: (nginx_enable | bool and nginx_install_from == 'nginx_repository')
        or nginx_amplify_enable | bool
  tags: nginx_key

- name: "{{ nginx_setup | capitalize }} NGINX"
  when: nginx_enable | bool
  tags: nginx_enable
  block:
    - name: "{{ nginx_setup | capitalize }} NGINX Open Source"
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/opensource/install-oss.yml"
      when: nginx_type == 'opensource'
      tags: nginx_install_oss

    - name: "{{ nginx_setup | capitalize }} NGINX dynamic modules"
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/modules/install-modules.yml"
      when:
        - nginx_modules is defined
        - nginx_modules | length > 0
      tags: nginx_install_modules

    - name: Modify systemd parameters
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/config/modify-systemd.yml"
      when:
        - ansible_facts['service_mgr'] == 'systemd'
        - nginx_service_modify | bool
      tags: nginx_modify_systemd

- name: Custom nginx configurations
  become: true
  when:
    - nginx_enable | bool
    - nginx_custom_enable | bool
  tags: nginx_custom_enable
  block:
    - name: Ensure configuration directories
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/config/ensure-directories.yml"
      tags: nginx_config_directories

    - name: Setup Diffie-Hellman file
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/config/setup-dhparam.yml"
      tags: nginx_config_dhparam

    - name: Nginx add errors html pages
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/modify/setup-error-html.yml"
      tags: nginx_config_error

    - name: Nginx configuration snippets
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/modify/setup-snippets.yml"
      tags: nginx_config_snippets

    - name: Nginx custom default configuration
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/modify/setup-default-config.yml"
      tags: nginx_config_default

    - name: Nginx configuration default site
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/modify/setup-default-site-config.yml"
      tags: nginx_config_default_site

    - name: Nginx custom default index.html page
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/modify/setup-default-html.yml"
      tags: nginx_config_default_html

    - name: Nginx setup virtual hosts configuration
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/modify/setup-proxy-site-config.yml"
      loop: "{{ nginx_proxy_sites_config | dict2items }}"
      loop_control:
        loop_var: proxy_sites_config
      tags: nginx_proxy_sites_config
      when:
        - proxy_sites_config is defined
        - proxy_sites_config | length > 0

  notify: (Handler) Start/reload NGINX

- name: Trigger handlers if necessary
  ansible.builtin.meta: flush_handlers

- name: Debug NGINX output
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/config/debug-output.yml"
  when:
    - nginx_enable | bool
    - nginx_debug_output | bool
    - nginx_state != 'absent'
  tags: nginx_debug_output

- name: Configure logrotate for NGINX
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/config/setup-logrotate.yml"
  when:
    - nginx_logrotate_conf_enable | bool
    - nginx_state != 'absent'
  tags: nginx_logrotate_config

- name: Install NGINX Amplify
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/amplify/install-amplify.yml"
  when:
    - nginx_amplify_enable | bool
    - nginx_amplify_api_key is defined
    - nginx_amplify_api_key | length > 0
  tags: nginx_install_amplify
