---
- name: Ensure the directories for Nginx configurations
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    recurse: true
    owner: root
    group: root
    mode: '0755'
  with_items:
    - "{{ nginx_snippets_dir }}"
    - "{{ nginx_sites_default_dir }}"
    - "{{ nginx_sites_available_dir }}"
    - "{{ nginx_sites_enabled_dir }}"
    - "{{ nginx_html_www_dir }}"
    - "{{ nginx_html_error_dir }}"

- name: Ensure Nginx log directory exist
  ansible.builtin.file:
    path: "{{ nginx_log_dir }}"
    state: directory
    recurse: true
    owner: root
    group: root
    mode: "0755"

- name: Ensure Nginx cache directory exist
  ansible.builtin.file:
    path: "{{ nginx_cache_dir }}"
    state: directory
    recurse: true
    owner: root
    group: root
    mode: "0755"
