---
- name: Ensure the directories for Nginx configurations
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  loop:
    - "{{ nginx_snippets_dir }}"
    - "{{ nginx_sites_default_dir }}"
    - "{{ nginx_sites_available_dir }}"
    - "{{ nginx_sites_enabled_dir }}"
    - "{{ nginx_sites_auth_dir }}"
    - "{{ nginx_html_www_dir }}"
    - "{{ nginx_html_error_dir }}"
    - "{{ nginx_log_dir }}"
    - "{{ nginx_cache_dir }}"
    - "{{ nginx_ssl_dir }}"
    - "{{ nginx_letsencrypt_dir }}"
