---
- name: Template a file, create Nginx error snippets conf
  ansible.builtin.template:
    src: nginx/snippets/error.conf.j2
    dest: "{{ nginx_snippets_dir }}/error.conf"
    owner: root
    group: root
    mode: '0644'
  no_log: true
  failed_when: false

- name: Template a file, create Nginx error http snippets conf
  ansible.builtin.template:
    src: nginx/snippets/error-http.conf.j2
    dest: "{{ nginx_snippets_dir }}/error-http.conf"
    owner: root
    group: root
    mode: '0644'
  no_log: true
  failed_when: false

- name: Template a file, create Nginx general snippets conf
  ansible.builtin.template:
    src: nginx/snippets/general.conf.j2
    dest: "{{ nginx_snippets_dir }}/general.conf"
    owner: root
    group: root
    mode: '0644'
  no_log: true
  failed_when: false

- name: Template a file, create Nginx compression snippets conf
  ansible.builtin.template:
    src: nginx/snippets/compression.conf.j2
    dest: "{{ nginx_snippets_dir }}/compression.conf"
    owner: root
    group: root
    mode: '0644'
  no_log: true
  failed_when: false

- name: Template a file, create Nginx security snippets conf
  ansible.builtin.template:
    src: nginx/snippets/security.conf.j2
    dest: "{{ nginx_snippets_dir }}/security.conf"
    owner: root
    group: root
    mode: '0644'
  no_log: true
  failed_when: false

- name: Template a file, create Nginx proxy snippets conf
  ansible.builtin.template:
    src: nginx/snippets/proxy.conf.j2
    dest: "{{ nginx_snippets_dir }}/proxy.conf"
    owner: root
    group: root
    mode: '0644'
  no_log: true
  failed_when: false

# - name: Template a file, create Nginx ssl snippets conf
#   ansible.builtin.template:
#     src: nginx/snippets/ssl.conf.j2
#     dest: "{{ nginx_snippets_dir }}/ssl.conf"
#     mode: u=rw,g=r,o=r
#   no_log: true
#   failed_when: false
